from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing import List, Optional
from pydantic import Field
from .common import SchemaBase

class ActionType(str, Enum):
    """Controlled vocabulary for experiment actions."""
    IDENTIFY = "identify"
    PICK = "pick"
    OPEN = "open"
    CLOSE = "close"
    TRANSFER = "transfer"
    MIX = "mix"
    SEAL = "seal"
    PLACE = "place"
    RELEASE = "release"
    CONFIRM = "confirm"
    UNKNOWN = "unknown"

class ActionEvent(SchemaBase):
    """High-level event generated by the action-recognition layer."""
    event_id: str = Field(
        min_length=1,
        description="Unique ID for this action event.",
    )
    actor_id: str = Field(
        min_length=1,
        description="Operator identifier.",
    )
    action: ActionType = Field(
        description="Recognized action.",
    )
    object_id: Optional[str] = Field(
        default=None,
        description="Object involved in the action.",
    )
    tool_id: Optional[str] = Field(
        default=None,
        description="Tool involved in the action.",
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence of the complete action interpretation.",
    )
    timestamp: datetime = Field(
        description="UTC timestamp at which the action was emitted.",
    )
    start_timestamp: Optional[datetime] = Field(
        default=None,
        description="Estimated start time of the action.",
    )
    end_timestamp: Optional[datetime] = Field(
        default=None,
        description="Estimated end time of the action.",
    )
    frame_start: Optional[int] = Field(default=None, ge=0)
    frame_end: Optional[int] = Field(default=None, ge=0)
    zone: Optional[str] = Field(
        default=None,
        description="Interaction zone.",
    )
    supporting_track_ids: List[int] = Field(
        default_factory=list,
        description="Track IDs supporting this action interpretation.",
    )